<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tc="http://ejemplo.org/tiposComunes"
           targetNamespace="http://ejemplo.org/consultores"
           xmlns="http://ejemplo.org/consultores"
           elementFormDefault="qualified">

  <xs:import namespace="http://ejemplo.org/tiposComunes" schemaLocation="tiposComunes.xsd"/>

  <xs:simpleType name="CCDType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][0-9]{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="consultorType">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="sexo" type="xs:string"/>
      <xs:element name="contacto">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="email" type="tc:emailType"/>
            <xs:element name="telefono" type="tc:telefonoType"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="departamento" type="xs:string"/>
      <xs:element name="empresaExterna" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="CCD" type="CCDType" use="required"/>
  </xs:complexType>

  <xs:element name="consultor" type="consultorType"/>
</xs:schema>
